#Tasks settings
DESTINATION_TIME = (5, 10)
DIREKTIV_TIME = (40, 100)
EXECUTION_TIME = (1,20)

#EGA settings
POPULATION_SIZE = 20
COUNT_OF_GENERATIONS = 30
CROSSOVER_CHOISE = 0
MATATION_COEF = 0
REPLACE_COEF = 0.5
ELITE_COEF=0.3
CHOOSE_RANDOM_CROSSOVER =0  # 0 - PMX  /  1 - RANDOM


#global settings
NUM_OF_EXPERIMENTS = 10
